! LDCOMB, loadCase1, loadCase2, loadCase3, loadCase4, loadCase5, coef1, coef2, coef3, coef4, coef5
! LDCOMB,      arg1,      arg2,      arg3,      arg4,      arg5,  arg6,  arg7,  arg8,  arg9,  ar10




*if,arg5,NE,0,THEN
    lc1=arg1
    cf1=arg5
*elseif,arg6,NE,0,THEN
    lc1=arg2
    cf1=arg5
*elseif,arg6,NE,0,THEN
    lc1=arg3
    cf1=arg5
*elseif,arg6,NE,0,THEN
    lc1=arg4
    cf1=arg5
*elseif,arg6,NE,0,THEN
    lc1=arg5
    cf1=arg5
*else
    'return zero'
*endif








