! AFUNRESTORE
! AFUNRESTORE

! Description:
! Restores the *AFUN setting to the value last backed up by AFUNBACKUP.

! Arguments:
! -

! Local parameters:
! -

! Global parameters:
! afunBackup_
! _OUTPUT


parverify,,'afunBackup_','CHAR'

*if,_OUTPUT,eq,1,then
    *if,upcase(afunBackup_),eq,'DEG',then
        ! Set to degrees
        *afun,'DEG'
        *del,afunBackup_,,nopr
        *return,-1
    *endif
*endif

! Default behavior: set to radians
*afun,'RAD'
*del,afunBackup_,,nopr
