! APPND, array, atom
! APPND,  arg1, arg2

! AR20: parType
! AR21: parLen
! AR22: newLen

! CONS_ARR_temp

*get,AR20,PARM,%arg1%,TYPE

*if,AR20,EQ,-1,THEN
    *del,%arg1%
    *dim,%arg1%,ARRAY,1
    %arg1%(1)=arg2
*else
    *get,AR21,PARM,%arg1%,DIM,X
    AR22=AR21+1
    *del,CONS_ARR_temp
    *vfun,CONS_ARR_temp,COPY,%arg1%
    *del,%arg1%
    *dim,%arg1%,ARRAY,AR22
    *vfun,%arg1%(1),COPY,CONS_ARR_temp
    %arg1%(AR22)=arg2
    *del,CONS_ARR_temp
*endif


