! arxori , orientation
! ARXORI , ARG1

! Description:
! Makes selected areas point towards or against the orientation of X axis in the active coordinate
! system.

! Arguments:
! ARG1: orientation  -  determines where areas should point:
!                         [>0] point towards X (default)
!                         [<0] point against X

! Local parameters:
! ar21: sign


! Parse inputs
ar21 = 1
*if,ARG1,ne,0,then
  ar21 = ARG1
*endif

! Orient areas
arori , 'x' , ar21
