! arzori , orientation
! ARZORI , ARG1

! Description:
! Makes selected areas point towards or against the orientation of Z axis in the active coordinate
! system.

! Arguments:
! ARG1: orientation  -  determines where areas should point:
!                         [>0] point towards Z (default)
!                         [<0] point against Z

! Local parameters:
! ar21: sign


! Parse inputs
ar21 = 1
*if,ARG1,ne,0,then
  ar21 = ARG1
*endif

! Orient areas
arori , 'z' , ar21
