! cdate , strTime
! CDATE , ARG1

! Description:
! Returns current date as a formatted string DD/MM/YY.

! Arguments:
! ARG1: parm  -  parameter name (string)

! Local parameters:
! ar20: numDate
! ar21: strDate
! ar21: strYear
! ar22: strMonth
! ar23: strDay


*get,ar20,active,,dbase,ldate

ar21 = chrval(ar20)

ar22 = strsub(ar21,3,2)
ar23 = strsub(ar21,5,2)
ar24 = strsub(ar21,7,2)

%ARG1% = strcat(strcat(ar24,'/'),strcat(strcat(ar23,'/'),ar22))
