! CSHELL_NX
! CSHELL_NX

! Description:
! Plots SHELL181 normal force along X axis diagram (N11).

! Arguments:
! -

! Local parameters:
! AR21: seqn_N11
! AR23: unitScaleFactor
! AR24: nameKey

AR21=1

AR23=1e-3
AR24='NX'

etable,'TMP_%AR24%',smisc,AR21

sadd,'SHELL_%AR24%','TMP_%AR24%',,AR23

etable,'TMP_%AR24%',eras

*cfopen,shelldiagram_tmp,tmp
    *vwrite,'SHELL_%AR24%','avg'
pletab,%C,%C
*cfclos
/nopr
/input,shelldiagram_tmp,tmp
/delete,shelldiagram_tmp,tmp
/gopr

