! csnext , output
! CSNEXT , ARG1

! Description:
! Returns a valid number to which no coordinate system is yet assigned.

! Arguments:
! ARG1: output  -  name of the parameter to which the result will be assigned (defaults to _OUTPUT)

! Local parameters:
! ar21: maxCS
! ar22: outputParm


parverify,'CSNEXT_VAR_check',ARG1,'CHAR'
*if,CSNEXT_VAR_check,eq,1,then
    ar22 = ARG1
*else
    ar22 = '_OUTPUT'
*endif

*get,ar21,cdsy,,num,max

*del,%ar22%,,nopr
%ar22%=((ar21+1)>11)

