! DFCZ188,Scale
! DFCZ188,arg1,arg2

! Lista de argumentos:
! arg1: Scale (fator de escala do diagrama)

! Lista de variáveis:
! AR20: ScaleFactor
! AR21: ETIndex
! AR23: Index
! AR24: ETName

AR23=5
AR24='DFCZ188'

*if,arg1,EQ,0,THEN
   AR20=1
*else
   AR20=arg1
*endif

ETINDEX,AR24
AR21=_OUTPUT
*if,AR21,EQ,0,THEN
   ETABLE,AR24,SMISC,AR23
*else
   ETABLE,REFL
*endif

DFCZ188_VAR_ETIndex=AR24
PLLS,DFCZ188_VAR_ETIndex,DFCZ188_VAR_ETIndex,AR20,,arg2




