! DFN188,Scale,kund
! DFN188,arg1,arg2

! Lista de argumentos:
! arg1: Scale (fator de escala do diagrama)

! Lista de variáveis:
! AR20: ScaleFactor
! AR21: ETIndex
! AR23: Index
! AR24: ETName

AR23=1
AR24='DFN188'

*if,arg1,EQ,0,THEN,
   AR20=1
*else
   AR20=arg1
*endif

ETINDEX,AR24
AR21=_OUTPUT
*if,AR21,EQ,0,THEN
   ETABLE,AR24,SMISC,AR23
*endif

DFN188_VAR_ETIndex=AR24
PLLS,DFN188_VAR_ETIndex,DFN188_VAR_ETIndex,AR20,arg2


