! DNY181,Scale
! DNY181,arg1

! Lista de argumentos:
! arg1: Scale (fator de escala do diagrama)

! Lista de variáveis:
! AR20: ScaleFactor
! AR21: ETIndex
! AR23: Index
! AR24: ETName

AR23=2
AR24='DNY181'

*if,arg1,EQ,0,THEN,
   AR20=1
*else
   AR20=arg1
*endif

ETINDEX,AR24
AR21=_OUTPUT
*if,AR21,EQ,0,THEN
   ETABLE,AR24,SMISC,AR23
*endif

DNY181_VAR_ETIndex=AR24
PLETAB,DNY181_VAR_ETIndex,AVG

