! GO2PNGV,  res
! GO2PNGV, arg1

! Descrição:
! Redireciona saída gráfica para imagem .png.

! Lista de argumentos:
! arg1: res  -  resolução da imagem (padrão: 2400)

! Lista de variáveis:
! -

/show,PNG,,1

*if,arg1,GT,0,THEN
   /gfile,arg1
*else
   /gfile,2400
*endif

/cmap,_TEMPCMAP_,CMP,,SAVE
/rgb,INDEX,100,100,100, 0
/rgb,INDEX, 80, 80, 80,13
/rgb,INDEX, 60, 60, 60,14
/rgb,INDEX, 0, 0, 0,15

