! NMAXY

! Lista de variáveis
! AR20: NCount
! AR21: yValues
! AR22: NDIndex
! AR23: PrevND
! AR24: MaxY

*get,AR20,NODE,0,COUNT
*del,VAR21,,nopr
*dim,VAR21,,AR20
AR23=0
! Para cada node selecionado:
*do,AR22,1,AR20,1
   AR23=NDNEXT(AR23)
   ! Obter (e armazenar no vetor) o valor da coordenada Y desse node
   VAR21(AR22)=NY(AR23)
*enddo
! Obter menor valor de coordenada Y armazenado no vetor
*vscfun,AR24,MAX,VAR21
! Atribuir valor à variável de saída
_OUTPUT=AR24

