! WINDEFA, window

!/window,arg1

/plopts,info,3
/plopts,LEG1,1
/plopts,LEG2,1
/plopts,LEG3,1
/plopts,FRAME,1
/plopts,TITLE,1
/plopts,MINM,0
/plopts,FILE,1
/plopts,SPNO,0
/plopts,LOGO,on
/plopts,WINS,on
/plopts,WP,0
/plopts,DATE,0
/triad,on


/udoc,arg1,cntr,bottom
/udoc,arg1,type,left
/udoc,arg1,typ2,left
/udoc,arg1,inum,left
/udoc,arg1,gwin,left
/udoc,arg1,view,0
/udoc,arg1,misc,0

/gformat,defa
