! WPSLICEXZ, y, sepo
! WPSLICEXZ, arg1, arg2

! Description:
! Divides all selected areas at the working plane (positioned according to arg1=y)

! Position working plane
WPLANE,-1,,arg1,,1,arg1,,,arg1,1

! Hide working plane
WPSTYL,,,,,,,,0

! Divide areas
*if,arg2,eq,1,then
    ASBW,ALL,sepo,DELETE
*else
    ASBW,ALL,,DELETE
*endif

! Reset working plane to original location
WPCSYS,-1,0

! Hide working plane
WPSTYL,,,,,,,,0


